f = open("info.txt", "a")
f.truncate(0)
studentid = input("Enter your student ID.\n")
courseid = input("Enter your course ID.\n")
professor = input("Enter your professor's lastname.\n")
f.write("studentid = "+str(studentid)+"\n")
f.write("courseid = "+str(courseid)+"\n")
f.write("professor = "+str(professor)+"\n")
f.close()
print("Setup complete! Run overlay.py to use the overlay.")
exit()
